import "./globals.css";
import footerStyles from "@/app/styles/footer.module.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { Baloo_Bhai_2 } from "next/font/google";

const baloo = Baloo_Bhai_2({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={baloo.className}>
        <div className={footerStyles.body}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
